### ISSUE TITLE
Python requirements issue

### ISSUE THREAD

**Issue by stacysimpson** [kaltura-vpaas/webcasting-app-python#7]
https://github.com/kaltura-vpaas/webcasting-app-python/blob/master/requirements.txt#L17

`ERROR: Could not find a version that satisfies the requirement KalturaClient==1.0.0 (from -r requirements.txt (line 17)) (from versions: none)
ERROR: No matching distribution found for KalturaClient==1.0.0 (from -r requirements.txt (line 17))`

**Comment by pfuternik** [comment]
This has been removed from requirements.
